import { Option } from '../../models/option.model';

export const DROPDOWN_OPTIONS: Option[][] = [
  [
    { value: 'Option 1', id: 'option_1' },
    { value: 'Option 2', id: 'option_2' },
    { value: 'Option 3', id: 'option_3' },
    { value: 'Option 4', id: 'option_4' },
    { value: 'Option 5', id: 'option_5' },
    { value: 'Option 6', id: 'option_6' },
    { value: 'Option 7', id: 'option_7' },
    { value: 'Option 8', id: 'option_8' },
    { value: 'Option 9', id: 'option_9' },
    { value: 'Option 10', id: 'option_10' },
  ],
  [
    { value: 'Option 11', id: 'option_11' },
    { value: 'Option 12', id: 'option_12' },
    { value: 'Option 13', id: 'option_13' },
    { value: 'Option 14', id: 'option_14' },
    { value: 'Option 15', id: 'option_15' },
    { value: 'Option 16', id: 'option_16' },
    { value: 'Option 17', id: 'option_17' },
    { value: 'Option 18', id: 'option_18' },
    { value: 'Option 19', id: 'option_19' },
    { value: 'Option 20', id: 'option_20' },
  ],
  [
    { value: 'Option 21', id: 'option_21' },
    { value: 'Option 22', id: 'option_22' },
    { value: 'Option 23', id: 'option_23' },
    { value: 'Option 24', id: 'option_24' },
    { value: 'Option 25', id: 'option_25' },
    { value: 'Option 26', id: 'option_26' },
    { value: 'Option 27', id: 'option_27' },
    { value: 'Option 28', id: 'option_28' },
    { value: 'Option 29', id: 'option_29' },
    { value: 'Option 30', id: 'option_30' },
  ],
  [
    { value: 'Option 31', id: 'option_31' },
    { value: 'Option 32', id: 'option_32' },
    { value: 'Option 33', id: 'option_33' },
    { value: 'Option 34', id: 'option_34' },
    { value: 'Option 35', id: 'option_35' },
    { value: 'Option 36', id: 'option_36' },
    { value: 'Option 37', id: 'option_37' },
    { value: 'Option 38', id: 'option_38' },
    { value: 'Option 39', id: 'option_39' },
    { value: 'Option 40', id: 'option_40' },
  ],
];
